sudo: required
services:
  - docker

before_install:
  - docker build -t satishbonam/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true satishbonam/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-058586967339"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
